### ISSUE TITLE
clone到自己的机器上，make build_armbian=y build出错

### ISSUE THREAD

**Issue by kerncoola** [qijianjun/build-beikeyun#2]
大神好，我clone到自己的机器上准备编译我家云的固件，执行make build_armbian=y build出现：
https://mirrors.tuna.tsinghua.edu.cn/armbian-releases/rock64/archive/Armbian_21.02.3_Rock64_focal_cu
rrent_5.10.21_xfce_desktop.img.xz:
2021-08-19 10:37:06 ERROR 404: Not Found.
https://mirrors.tuna.tsinghua.edu.cn/armbian-releases/rock64/archive/Armbian_21.02.3_Rock64_focal_cu
rrent_5.10.21_xfce_desktop.img.xz.sha:
2021-08-19 10:37:06 ERROR 404: Not Found.
make: *** [Makefile:35: ARMBIAN_PKG_UBUNTU_XFCE] Error 8
请问下这里怎么更改，另外自己编译固件有相关教程吗，谢谢。
我的系统版本：
Linux VM-12-5-ubuntu 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_
64 GNU/Linux

**Comment by MiltonLai** [comment]
你要看一下Makefile里的内容, 因为 https://mirrors.tuna.tsinghua.edu.cn/armbian-releases/rock64/archive/ 这个地址下的img是不断更新的, 现在已经到 Armbian_21.08.1 版本了, 你需要更新一下Makefile里对应的文件名, 然后再执行.

这个Makefile其实只是将原始img解包再加上贝壳云的dtb再打包,
